manifest:
  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  projects:
    - name: zephyr
      remote: zephyrproject-rtos
      revision: v3.7.2
      import:
        name-allowlist:
          - cmsis
          - cmsis_6
          - hal_nxp
          - hal_stm32
          - hal_nordic
          - hal_st
          - hal_espressif
          - mcuboot
          - tinycrypt
          - mbedtls
          - zcbor
          - littlefs
          - canopennode
          - open-amp
          - libmetal
          - loramac-node
          - fatfs
          - lvgl
